### ISSUE TITLE
Need help to make nvim-pager.py script work in kitty

### ISSUE THREAD

**Issue by ciscohack** [cdelledonne/dotfiles#1]
Hi cdelledonne,

I would be grateful if you could help me make your nvim-pager.py script work in my kitty. I tried the steps you have mentioned but unfortunately, it does not trigger the nvim pager on my kitty terminal. when I am pressing ctrl + shift +h or g nothing is happening 

Same way I tried your tab script and it's not producing the result that is working for you. if you could get spare time I request you to please help me. I am using a pager that is not good but wanted to try yours and hope that you could help

**Comment by cdelledonne** [comment]
Hi, what is your kitty configuration? If you launch `kitty` from another terminal, do you see any errors when pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>G</kbd>?

**Comment by ciscohack** [comment]
This is the config I am using.


##Kitty Setting to launch it from terminal
allow_remote_control yes
listen_on unix:/tmp/kitty

# Pager
action_alias launch_pager  launch --stdin-add-formatting --type=overlay
map ctrl+shift+g           launch_pager --stdin-source=@last_cmd_output ~/.config/kitty/nvim-pager.py -n "Last command output"
map ctrl+shift+h           launch_pager --stdin-source=@screen_scrollback ~/.config/kitty/nvim-pager.py -n "Scrollback history"


error I am getting this but don't understand what is dependency here with telescope ... ctrl + shift + g is not doing anything 

<img width="1425" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/88fa1de2-6ce9-443f-be83-d6ae111e5a17">

**Comment by cdelledonne** [comment]
It looks like the pager actually starts, these errors are from from within Neovim. The problem seems to be with your configuration of Neovim, as far as I can tell.

By the way, when I asked you to start `kitty` from another terminal, I meant this:

1. Start `kitty` from a terminal, let's call it terminal 1
2. This should launch `kitty` in another window, let's call it terminal 2
3. Now, from within terminal 2, run some command and then launch the pager with the shortcut
4. Go back to terminal 1 and see if any errors are reported

**Comment by ciscohack** [comment]
@cdelledonne Thanks a lot for your time and help. Yes, I ran the kitty from the Alacritty terminal. the telescope is nvim plugin for code suggestions but I don't think if we have Python script readymade then I should cause any problem Right?

And I ran the script as you mentioned in steps

**Comment by cdelledonne** [comment]
So no errors reported in Alacritty?

**Comment by ciscohack** [comment]
no there is no error.. only font error which is seems kitty bug to me
<img width="1421" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/6330fc76-4a1b-466a-aa61-4a0c14a33b01">

**Comment by cdelledonne** [comment]
Try adding this line just after line 18 in nvim-pager.py:

```python
    "-u", "NONE",
```

This tells Neovim to not load your init.vim configuration. The block should look something like this then:

```python
NVIM_CMD = [
    "/usr/bin/env",
    "nvim",
    "--cmd", "set shortmess+=I",            # Do not display intro message
    "--cmd", "set clipboard+=unnamedplus",  # Use system clipboard by default
    "--noplugin",
    "-u", "NONE",
]
```

Let me know if this changes anything.

**Comment by ciscohack** [comment]
ok thanks. Let me try this

**Comment by ciscohack** [comment]
@cdelledonne, Now the error is gone. But now it's not loading things in nvim buffer ... buffer is empty and I don't know why but ctrl  + shift + g et shortcut is not doing any thing only H option working

<img width="873" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/86515452-cb94-4e5f-b6f8-4376ea6e4a1d">

**Comment by cdelledonne** [comment]
Did you run some commands in the terminal before using the pager? The pager can only show something when there is some history in the terminal.

**Comment by ciscohack** [comment]
yes, indeed I ran some commands multiple times

**Comment by cdelledonne** [comment]
You're running on macOS I suppose? There might be some problems creating a socket that kitty uses to communicate with Neovim.

Inside of nvim-pager.py, replace line 37

```python
    socket = Path(f"/run/user/{os.getuid()}/nvim-pager-{os.getpid()}")
```

with this one

```python
    socket = Path(f"/tmp/nvim-pager-{os.getpid()}")
```

Let me know if this changes anything.

**Comment by ciscohack** [comment]
Yes running macos 14. let me try this

**Comment by ciscohack** [comment]
@cdelledonne you are awesome. issue resolved and now working fine but why ctrl+shift+g key map is not working .. how to fix this last part

**Comment by cdelledonne** [comment]
Sounds like kitty's [shell integration feature](https://sw.kovidgoyal.net/kitty/shell-integration/) is not working properly for you. I'm not sure why's that though, you'll have to check out kitty's documentation and try to browse existing issues in the kitty repo.

**Comment by ciscohack** [comment]
> Sounds like kitty's [shell integration feature](https://sw.kovidgoyal.net/kitty/shell-integration/) is not working properly for you. I'm not sure why's that though, you'll have to check out kitty's documentation and try to browse existing issues in the kitty repo.

ok many thanks to you. btw is there some similar issue with tab_bar.py as the result that I shared with you last time does not matches to your result

**Comment by cdelledonne** [comment]
Can you be more specific? What do you mean here as my result? And what is not matching your results?

**Comment by ciscohack** [comment]
> Can you be more specific? What do you mean here as my result? And what is not matching your results?

talking about this discussion we had here "https://github.com/kovidgoyal/kitty/discussions/4447" I shared the screenshot for reference with you that my tab bar not look similar as your one shared in the post

**Comment by ciscohack** [comment]
here is SS of your tab bar.. round 
<img width="922" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/1cd82072-c5c5-4266-ace6-18c70db4b9ab">

<img width="908" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/4120a4cc-29bf-4687-b2e3-c2fd12ef2db6">


Mine tab bar missing rounded shape

<img width="854" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/8f0035fd-cc17-4a9b-98f5-8207647ee10b">

**Comment by cdelledonne** [comment]
Does your kitty.conf have these options set?

```
tab_bar_edge                    top
tab_bar_margin_width            5.0
tab_bar_margin_height           7.5 7.5
tab_bar_style                   custom
tab_bar_align                   center
tab_bar_min_tabs                1
tab_title_template              "󰨸 {index} {title}"
active_tab_title_template       "󰅍 {index} {title}"
active_tab_font_style           normal
tab_bar_background              #303030
tab_bar_margin_color            #303030
```

**Comment by cdelledonne** [comment]
Particularly the option `tab_bar_style custom`

**Comment by ciscohack** [comment]
Yes mimic the exact same configuration as yours

**Comment by cdelledonne** [comment]
And if you start `kitty` from another terminal, do you see any errors in this other terminal? Can I see the output of that?

**Comment by ciscohack** [comment]
<img width="1295" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/f0d7ccd6-5c68-4ecb-8423-d5f56718b849">

<img width="1682" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/16687958-d4e0-417e-a01e-b8cb511d376e">

**Comment by ciscohack** [comment]
Requirement already satisfied: paramiko in /opt/homebrew/lib/python3.11/site-packages (3.3.1)
Requirement already satisfied: bcrypt>=3.2 in /opt/homebrew/lib/python3.11/site-packages (from paramiko) (4.0.1)
Requirement already satisfied: cryptography>=3.3 in /opt/homebrew/lib/python3.11/site-packages (from paramiko) (41.0.4)
Requirement already satisfied: pynacl>=1.5 in /opt/homebrew/lib/python3.11/site-packages (from paramiko) (1.5.0)
Requirement already satisfied: cffi>=1.12 in /opt/homebrew/lib/python3.11/site-packages (from cryptography>=3.3->paramiko) (1.16.0)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=3.3->paramiko)

**Comment by ciscohack** [comment]
I have python 3.11. is it because of this having this error

**Comment by cdelledonne** [comment]
How did you install `paramiko`? Is it a user installation? No virtual environments right? And how did you install kitty? How do you run kitty?

**Comment by ciscohack** [comment]
yes, I don't have a virtual environment.  python 3.11 installed through brew and for kitty I used dmg file and install then launched the kitty terminal from the application ..

paramiko I installed by simply running "pip install paramiko" command

**Comment by cdelledonne** [comment]
Mhh I think the macOS installation of kitty (using the dmg package) does not look into the python packages installed locally, because that kitty uses its own python. See this discussion: https://github.com/kovidgoyal/kitty/discussions/4610

I don't have a macOS system to test things, but I would try this: uninstall kitty, and then reinstall it using brew: `brew install --cask kitty`. See if this installation of kitty uses system python, and solves your issue.

Otherwise I have no other suggestions unfortunately. You can modify tab_bar.py to just bypass the functionality provided by paramiko, so for instance you can have the function `_get_system_info()` always return local user and host, even when within an SSH connection.

**Comment by ciscohack** [comment]
@cdelledonne ok let me install it through brew then and update you

**Comment by ciscohack** [comment]
@cdelledonne one quick question last time I installed by this method.. this also refer system python

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
    installer=nightly

**Comment by cdelledonne** [comment]
I actually don't know if installing kitty with this method makes it use system python, but I suspect not

**Comment by ciscohack** [comment]
@cdelledonne No worries, just installed the kitty as you suggested with brew and the result and error is the same

<img width="1389" alt="image" src="https://github.com/cdelledonne/dotfiles/assets/11479557/89766ac9-05b0-41a0-904f-7b69f9b84719">

**Comment by cdelledonne** [comment]
Ok, then I really can't help you much. You can always of course get the source code of the paramiko library and copy the `SSHConfig` class into your tab_bar.py, instead of trying to import it.

**Comment by ciscohack** [comment]
@cdelledonne OK no issue thanks a lot
